### ISSUE TITLE
Utvide public-service og service med 'produserer'

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/service-catalog#42]
- [x] Utvid modellen til public-service og service med dette 👇

```
produces: {
  title: LanguageStrings,
  description: LanguageStrings,
  identifier: string,
  language: string[],
  type: string[],
}
```

- [x] Oppdater rdf med `cv:produces` som peker på subjektet til tjenesteresultat.
- [ ] Kontaktpunktet skal ha `dct:title` og`dct:identifier` i rdf. Bør ha `dct:description` og `dct:language`. Kan ha `dct:type`

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/service-catalog/pull/45
